# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pJpuiLK-aWWGXn8p68s3hE1U-2fkJ2pK
"""

import random
import string

def generar_contrasena(longitud, numeros, mayusculas, simbolos):

    caracteres = string.ascii_lowercase

    if numeros:
        caracteres += string.digits

    if mayusculas:
        caracteres += string.ascii_uppercase

    if simbolos:
        caracteres += "!@#$%&*?"

    contrasena = ""

    for i in range(longitud):
        contrasena += random.choice(caracteres)

    return contrasena


def evaluar_seguridad(contrasena):

    puntos = 0

    if len(contrasena) >= 8:
        puntos += 1

    if any(c.isdigit() for c in contrasena):
        puntos += 1

    if any(c.isupper() for c in contrasena):
        puntos += 1

    if any(c in "!@#$%&*?" for c in contrasena):
        puntos += 1

    if puntos >= 3:
        return "FUERTE"
    else:
        return "DÉBIL"


print("=== CIPHERSOUND ===")

longitud = int(input("Longitud de la contraseña: "))

numeros = input("¿Incluir números? (s/n): ").lower() == "s"
mayusculas = input("¿Incluir mayúsculas? (s/n): ").lower() == "s"
simbolos = input("¿Incluir símbolos? (s/n): ").lower() == "s"

contrasena = generar_contrasena(
    longitud,
    numeros,
    mayusculas,
    simbolos
)

resultado = evaluar_seguridad(contrasena)

print("\nContraseña generada:")
print(contrasena)

print("\nNivel de seguridad:")
print(resultado)

if resultado == "FUERTE":
    print("🔊 Sonido de éxito activado")
else:
    print("⚠️ Sonido de advertencia activado")
